#!/bin/sh
USER_DATA_DIR="${HOME}/.minecraft"
mkdir -p "${USER_DATA_DIR}" "${CACHE_DIR}" 2>/dev/null

exec bwrap \
    --cap-drop ALL --unshare-user-try --unshare-pid --unshare-cgroup-try  \
    --ro-bind /usr /usr \
    --ro-bind /lib64 /lib64 \
    --ro-bind /etc/localtime /etc/localtime \
    --ro-bind /etc /etc \
    --dev-bind /dev /dev \
    --ro-bind /sys /sys \
    --proc /proc \
    --tmpfs /tmp \
    --bind /run/user/$(id -u) /run/user/$(id -u) \
    --dev-bind /run/dbus /run/dbus \
    --bind "${USER_DATA_DIR}" "${HOME}/.minecraft" \
    --setenv HOME "${HOME}" \
    --setenv XDG_RUNTIME_DIR "/run/user/$(id -u)" \
    --setenv LIBGL_ALWAYS_SOFTWARE "0" \
    --bind /var/tmp /var/tmp \
    --ro-bind /usr/share/fonts /usr/share/fonts \
    --ro-bind /usr/share/icons /usr/share/icons \
    --ro-bind /usr/share/mime /usr/share/mime \
    --ro-bind /opt/minecraft-launcher /opt/minecraft-launcher \
    --share-net \
    --new-session \
    --die-with-parent \
    bash
    #/opt/minecraft-launcher/minecraft-launcher "$@"
