[__config__]
# Version records file to be committed by GitHub Actions
oldver = "../old_versions.json"
newver = "../new_versions.json"

["app-i18n/rime-ice"]
source = "github"
github = "iDvel/rime-ice"

["app-misc/bilihud"]
source = "github"
github = "locez/bilihud"

["dev-python/browser-cookie3"]
source = "pypi"
pypi = "browser-cookie3"

["dev-python/pure-protobuf"]
source = "pypi"
pypi = "pure-protobuf"

["net-misc/tsshd"]
source = "github"
github = "trzsz/tsshd"
use_latest_release = true
prefix = "v"

["sys-kernel/cachyos-sources"]
source = "github"
github = "CachyOS/linux"
use_max_tag = true
include_regex = "cachyos-[0-9]+\\.[0-9]+\\.[0-9]+-[0-9]+"
from_pattern = "^cachyos-"
to_pattern = ""

["sys-kernel/xanmod-sources"]
source = "gitlab"
gitlab = "xanmod/linux"
use_max_tag = true
include_regex = "[0-9]+\\.[0-9]+\\.[0-9]+-xanmod[0-9]+"
from_pattern = "-xanmod[0-9]+$"
to_pattern = ""
